### ISSUE TITLE
XSS in mod details view

### ISSUE THREAD

**Issue by amahlaka** [RedstoneWizard08/Wormhole#1]
![image](https://user-images.githubusercontent.com/13930236/224472627-5fb96733-abfb-4eaa-97d2-200681d364ed.png)
if the mod description contains HTML, it gets rendered in the wormhole app

**Comment by Rexicon226** [comment]
a real issue ^^, extremely difficult to find ^^. please hire this man

**Comment by RedstoneWizard08** [comment]
I'll fix this

**Comment by RedstoneWizard08** [comment]
Fixed in commit #9f7bd11
